name = "SimpleDirectedHypergraphs"
uuid = "a42c6b43-640c-4761-b4a8-4f98c31d02e9"
authors = ["Evan Walter Clark Spotte-Smith"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleHypergraphs = "aa4a32ff-dd5d-5357-90e3-e7a9512f0501"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
DataStructures = "^0.18.11"
GLPK = "1.2.1"
Graphs = "1.12.0"
InvertedIndices = "1.3.1"
JSON3 = "^1.0.1"
JuMP = "1.29.2"
LinearAlgebra = "^1.6.7"
SimpleHypergraphs = "0.3.0"
SimpleTraits = "^0.9.4"
StatsBase = "^0.34.0"
StructTypes = "^1.0.1"
julia = "^1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
